/*******************************************************************************
 * Copyright 2015
 * Ubiquitous Knowledge Processing (UKP) Lab
 * Technische Universität Darmstadt
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package eu.kidf.diversicon.core;

import de.tudarmstadt.ukp.lmf.model.semantics.SynsetRelation;
import eu.kidf.diversicon.data.DivUpper;

/**
 * Holds some extra field for S-Match
 * 
 * 
 * See <a href=
 * "https://github.com/dkpro/dkpro-uby/blob/master/de.tudarmstadt.ukp.uby.lmf.model-asl/src/main/java/de/tudarmstadt/ukp/lmf/model/enums/ERelNameSemantics.java"
 * target="_blank"> ERelNameSemantics</a> for possible relation names.
 * 
 * @since 0.1.0
 */
public class DivSynsetRelation extends SynsetRelation {

	protected int depth;

	protected String provenance;
	
	/**
	 * Copies all the fields of {@code sr into this object}
	 */
	public DivSynsetRelation(SynsetRelation sr) {
	    this.setFrequencies(sr.getFrequencies());
	    this.setRelName(sr.getRelName());
	    this.setRelType(sr.getRelType());
	    this.setSource(sr.getSource());
	    this.setTarget(sr.getTarget());	    
	}

	public DivSynsetRelation() {
		super();
		this.depth = 1;
		this.provenance = "";
	}

	/**
	 * The identifier of source who produced the data. Must be unique worldwide.
	 * Defaults to "". Synthetic relations generated by Diversicon will have
	 * {@link DivUpper#PREFIX} as identifier.
	 */	
	public String getProvenance() {
		return provenance;
	}

	/**
	 * See {@link #getProvenance()}.
	 */
	public void setProvenance(String provenance) {
		this.provenance = provenance;
	}

	/**
	 * The depth of the relation, useful if it was computed for a transitive closure, otherwise 
	 * defaults to 1.  
	 */
	// TODO define semantics for self-loops, do they have depth 0 ?
	public int getDepth() {
		return depth;
	}

	/**
	 * See {@link #getDepth()}
	 */
	public void setDepth(int depth) {
		this.depth = depth;
	}

    @Override
    public String toString() {
        String sourceId = source == null ? "null" : source.getId();
        String targetId = target == null ? "null" : target.getId();
        
        return "DivSynsetRelation [depth=" + depth + ", provenance=" + provenance + ", source=" + sourceId + ", target="
                + targetId + ", relType=" + relType + ", relName=" + relName + ", frequencies=" + frequencies + "]";
    }
	
    /**
     * Returns a new UBY SynsetRelation that will be a shallow copy of this data structure
     * 
     * @since 0.1.0
     */
    public SynsetRelation toSynsetRelation(){
        SynsetRelation ret = new SynsetRelation();
        ret.setFrequencies(this.getFrequencies());
        ret.setRelName(this.getRelName());
        ret.setRelType(this.getRelType());
        ret.setSource(this.getSource());
        ret.setTarget(this.getTarget());            
        return ret;
    }

}
